require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });
const Groq = require('groq-sdk');
const { rag } = require('./rag');
const { liveRag } = require('./live-rag');
const QueryLog = require('./models/QueryLog');

class HybridRAGPipeline {
    constructor() {
        console.log("DEBUG: Initializing Hybrid Ensemble Synthesis Engine...");
        const groqKey = process.env.GROQ_API_KEY;
        this.groq = groqKey ? new Groq({ apiKey: groqKey }) : null;
    }

    async fetchQwenAnswer(queryText) {
        const apiUrl = process.env.FINETUNED_API_URL || 'https://madhusudhan001-qwen-materials-api.hf.space/v1/chat/completions';
        try {
            console.log("DEBUG: Querying Fine-tuned Qwen model...");
            const res = await fetch(apiUrl, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    model: "qwen2.5-0.5b",
                    messages: [
                        { role: "system", content: "You are a specialized Materials Science model." },
                        { role: "user", content: queryText }
                    ],
                    stream: false,
                    temperature: 0.7,
                    max_tokens: 512
                })
            });

            if (!res.ok) throw new Error(`Status ${res.status}`);
            const data = await res.json();
            return data.choices?.[0]?.message?.content || "(Qwen model produced empty output)";
        } catch (err) {
            console.warn("⚠️ Fine-tuned Qwen offline or failed:", err.message);
            return "(Fine-tuned Qwen model is currently offline or unreachable)";
        }
    }

    async *queryStream(queryText, history = [], user = null) {
        const startTime = Date.now();
        console.log("DEBUG: Starting Hybrid Ensemble query...");

        let pineconeAnswer = "Unavailable.";
        let qwenAnswer = "Unavailable.";
        let qdrantAnswer = "Unavailable.";
        let pineconeSources = [];
        let qdrantSources = [];

        try {
            // Run all three engines concurrently!
            const [pineconeRes, qwenRes, qdrantRes] = await Promise.all([
                rag.query(queryText).catch(e => { console.warn("Pinecone failed:", e); return { answer: "Failed to retrieve from Pinecone.", sources: [] }; }),
                this.fetchQwenAnswer(queryText).catch(e => "Failed to retrieve from Qwen."),
                liveRag.query(queryText).catch(e => { console.warn("Qdrant failed:", e); return { answer: "Failed to retrieve from Qdrant.", sources: [] }; })
            ]);

            pineconeAnswer = pineconeRes.answer || "No response.";
            pineconeSources = pineconeRes.sources || [];
            
            qwenAnswer = qwenRes || "No response.";
            
            qdrantAnswer = qdrantRes.answer || "No response.";
            qdrantSources = qdrantRes.sources || [];

            console.log("✅ Successfully retrieved candidate answers from all 3 pipelines.");

        } catch (e) {
            console.error("❌ Hybrid concurrent retrieval failed:", e.message);
        }

        const consolidatedSources = [...new Set([...pineconeSources, ...qdrantSources])].sort();

        // Construct Synthesis Prompt for Groq
        const synthesisPrompt = `You are an elite, research-grade hybrid scientific synthesis engine.
Your task is to analyze three distinct candidate answers generated by three different materials science AI agents and synthesize them into the single finest, most comprehensive, scientifically rigorous, and accurate answer possible.

Here are the three candidate responses:

---
AGENT 1: Quokka RAG Expert (Pinecone retrieval from specialized textbooks/materials database)
${pineconeAnswer}

---
AGENT 2: Fine-tuned Qwen Model (Adapters trained directly on specialized scientific instruction tuning sets)
${qwenAnswer}

---
AGENT 3: Qdrant Live RAG (Real-time web search via Serper.dev and cloud vector indexing)
${qdrantAnswer}
---

Your synthesis must strictly adhere to the following rules:
1. Reconcile any discrepancies or disagreements scientifically using proven materials science logic.
2. Select the most factually accurate, grounded, and numerically precise details from each response.
3. Eliminate any generic filler, repetitive claims, or unsupported hypotheses.
4. Structure the final response professionally using:
   - Overview (synthesizing established context)
   - Consolidated Key Properties / Findings (with numerical values, chemical formulas, and precise values)
   - Unified Mechanism / Explanation
   - Future Research / Applications
   - Consolidated Sources (uniquely merging the source lists from Pinecone and Qdrant)

RESPONSE STYLE:
- Rigorous
- Professional
- Authoritative
- Fact-driven`;

        const userGreeting = user ? `\n\nADDITIONAL INFO: The user you are talking to is named ${user.name}. Feel free to greet them by name!` : '';

        const messages = [
            {
                role: "system",
                content: synthesisPrompt + userGreeting
            }
        ];

        for (const msg of history) {
            messages.push({ role: msg.role || "user", content: msg.content || "" });
        }

        messages.push({ role: "user", content: queryText });

        let fullResponseContent = "";

        try {
            console.log("DEBUG: Initiating ensemble synthesis stream...");
            const stream = await this.groq.chat.completions.create({
                model: "llama-3.1-8b-instant",
                messages: messages,
                max_tokens: 2048,
                temperature: 0.5,
                stream: true
            });

            // Send sources upfront
            yield `data: ${JSON.stringify({ type: 'sources', sources: consolidatedSources })}\n\n`;

            for await (const chunk of stream) {
                if (chunk.choices && chunk.choices.length > 0) {
                    const delta = chunk.choices[0].delta.content || "";
                    if (delta) {
                        fullResponseContent += delta;
                        yield `data: ${JSON.stringify({ type: 'chunk', content: delta })}\n\n`;
                    }
                }
            }

            // Log query to MongoDB
            try {
                await QueryLog.create({
                    userId: user ? user.id : null,
                    userEmail: user ? user.email : 'guest',
                    query: queryText,
                    answer: fullResponseContent.substring(0, 1000),
                    sources: consolidatedSources,
                    responseTimeMs: Date.now() - startTime,
                    usedRagContext: consolidatedSources.length > 0,
                });
            } catch (logErr) {
                console.warn('Failed to save query log:', logErr.message);
            }

            yield `data: ${JSON.stringify({ type: 'done' })}\n\n`;

        } catch (e) {
            console.error("Ensemble synthesis failed:", e.message);
            const fallbackText = `**Hybrid Synthesis Offline** 🧠🔌\n\nThe synthesis model is temporarily busy. Here are the combined source references found:\n` + 
                consolidatedSources.map(s => `📄 *${s}*`).join('\n');
            yield `data: ${JSON.stringify({ type: 'chunk', content: fallbackText })}\n\n`;
            yield `data: ${JSON.stringify({ type: 'done' })}\n\n`;
        }
    }
}

const hybridRag = new HybridRAGPipeline();
module.exports = { hybridRag };
